name: 'Gitbook'
on:
  push:
    branches:
      - main
  label:
    types: [created,edited]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Gitbook Action          
      uses: ZanderZhao/gitbook-action@v1.2.4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_token: ${{ secrets.PERSONAL_TOKEN }
        publish_token: ${{ secrets.PERSONAL_TOKEN }
        git_name: 2096779623
        time_zone: Asia/Shanghai
        source_branch: main
        source_edit_time: true
        publish_push_force: true
